#!/bin/bash

if [[ -n $(ls -l $HOME/.default-java | grep openjdk) ]]
then
    cd
    unlink .default-java
    ln -s /usr/local/jdk1.7.0_51 .default-java
    echo '$JAVA_HOME now points to Oracle Java.'
else
    cd
    unlink .default-java
    ln -s /usr/lib/jvm/java-7-openjdk-amd64/ .default-java
    echo '$JAVA_HOME now points to OpenJDK.'
fi
